### ISSUE TITLE
update to 1.7.2

### ISSUE THREAD

**Issue by andreasplesch** [x3dom/component-editor#8]
The editor still works with 1.7.2, as it should:
https://rawgit.com/andreasplesch/component-editor/b3b664970c54a31812cf42c6f66cb0de313f2397/component_editor/index.html

**Comment by andreasplesch** [comment]
Well, not quite. Zooming with the mouse is broken in 1.7.2.

Still works with 1.7.1:
https://rawgit.com/andreasplesch/component-editor/188941f5daafdb9618e499027d43980d02b8b32e/component_editor/index.html

**Comment by mlimper** [comment]
That could have to do with some fixes for the turntable navigation (provided by @skluge) which came after the 1.7.2 release and are now in dev - could you try with dev?

**Comment by chmouton** [comment]
Max,
Do you think that it could be possible to allow the touch feature for the component editor?
Kind regards
Christophe

**Comment by mlimper** [comment]
Not sure how the standard navigation currently behaves on touch - the aim is, of course, that the turntable works also on touch. We need to check the current dev version to know if that's really the case.

**Comment by andreasplesch** [comment]
https://rawgit.com/andreasplesch/component-editor/47abe5f00153aab07849adf2d1b06fb0179ae140/component_editor/index.html

uses the dev build and zooming works ! But did not try with touch (I guess on a tablet ?).
